[package]
name = "fightchat"
version = "0.1.0"
authors = ["John Janes <john.janes@yello.co>"]

[dependencies]
actix = "0.5"
actix-web = "0.6"
env_logger = "*"
futures = "0.1"
tokio-core = "0.1"
diesel = { version = "1.0.0", features = ["postgres"] }

